### ISSUE TITLE
Помощь с переездом на более готовый движок

### ISSUE THREAD

**Issue by yoursweetginger** [haywiki/haywiki.github.io#22]
Привет.

Отличное наполнение сайта, но не хватает эстетики и функциональности. Есть готовый движок для документаций (в основном про технические) - [docusaurus](https://docusaurus.io/)
Я поднимал сайт такого же смысла, но по [Шри-Ланке.](https://github.com/ComradeAx0n/you-open-sri-lanka). Если считаешь нужным, то могу помочь с переездом на docusaurus, как руками так и словами.

**Comment by druidvav** [comment]
Не уверен, что у меня будет время заниматься еще и эстетикой :)
