### ISSUE TITLE
Информация по переоформлению лицевых счетов коммунальных ресурсов на себя при покупке квартиры

### ISSUE THREAD

**Issue by emischenko** [haywiki/haywiki.github.io#29]
**Газ:**
в своем филиале газпрома, найти можно здесь: https://armenia.gazprom.ru/branches/

После подачи заявления будет произведена замена счетчика газа (он как правило стоит в общих зонах и доступ в квартиру не требуется, но требуется присутствие собственника для подписания акта, счетчик меняется бесплатно, изменение имени в документах происходит только после замены счетчика и занимает до 3 месяцев! Ожидайте звонка, пригласят для подписания договора.

**Вода.**
Абовяна, 66а, запись в earlyone
Всё оформление происходит при вас, занимает 10-20 минут (руками заполняются документы)
Тут же можно написать заявление, если вода грязная или напор слабый

**Электричество.** 
Электросети Армении, ул. Арменака Арменакяна, 127, вход с улицы (во внутренний двор заходить не надо, хотя там красиво)
При вас заполняют заявление, далее в течение месяца позвонят и пригласят для подписания договора

Везде нужны документы:
- паспорт, желательно с нотариальным переводом
- распечатка выписки из кадастра о собственности
- желательно номер лицевого счета, можно узнать у старого хозяина
- если переоформление не личное, то требуется на того, кто пойдет написать рукописную доверенность (без заверения)

**Comment by druidvav** [comment]
Дополнил информацию в статье https://haywiki.org/life/buying-home.html

Спасибо!
