### ISSUE TITLE
Где купить продукты

### ISSUE THREAD

**Issue by emischenko** [haywiki/haywiki.github.io#30]
не нашел целевого раздела
крупные супермаркеты:
Сити
Супермаркет.ам
Нор-Зовк (у них онлайн можно заказать и шашлык, кебабы, на мой взгляд одни из вкуснейших, но минус - время доставки непрогнозируемо. иногда заказ могут просто проигнорить)
Сас
Циран

Также можно рекомендовать

https://t.me/erevanbuuz - релоканты делают замороженные Буузы, Хуушуры (типа чебуреков), пельмени. очень вкусно
https://www.facebook.com/groups/274732839916698/ - фермеры выкладывают объявления о продаже своей продукции, пока опыт очень положительный, по ценам часто в разы дешевле, чем в магазинах

**Comment by druidvav** [comment]
Раньше были в списке полезных контактов, но теперь много, поэтому выделил в отдельный раздел https://haywiki.org/life/grocery.html

Спасибо!
