### ISSUE TITLE
Покупка мебели

### ISSUE THREAD

**Issue by emischenko** [haywiki/haywiki.github.io#32]
Список магазинов

Ламито

Вега

Домус

россыпь магазинов по дороге в аэропорт

**Comment by Lizardy** [comment]
Добавлю пару магазинов по ул. Мелкумова в районе Ачапняк:
Коала в кольцеобразном здании (мебель из Беларуси)
Liarubkahuyq напротив отеля King (кухонные гарнитуры и рабочие столы на заказ)
