### ISSUE TITLE
Дополнения полезных ссылок

### ISSUE THREAD

**Issue by Lizardy** [haywiki/haywiki.github.io#41]
Сервис подписки на бумажные книги - как библиотека, только с доставкой https://archivarius.store/books/yerevan

Сообщество энтузиастов за чистый воздух в городах Армении - устанавливают датчики для измерения качества воздуха https://armaqi.org/

**Comment by druidvav** [comment]
https://github.com/haywiki/haywiki.github.io/commit/b4a8e46c0708fc3e224143f825abf13503e2fa1a
