### ISSUE TITLE
Проблема с комментами на сайте

### ISSUE THREAD

**Issue by Lizardy** [haywiki/haywiki.github.io#42]
Не удалось оставить коммент на сайте, пробовала залогиниться через яндекс ID, ошибка в консоли:
"Failed to load resource: the server responded with a status of 400 ()" https://anycomment.io/v2/user/login-token?app_id=4537&token=(значение токена убрала на всякий случай)

**Comment by druidvav** [comment]
К сожалению, сервис anycomment я исправить не могу :(
