### ISSUE TITLE
Дополнение в посылки- в Ереване посылка может придти в разные отделения

### ISSUE THREAD

**Issue by emischenko** [haywiki/haywiki.github.io#43]
Часто за дом могут отвечать 2 отделения, столкнулся с этим в Кентроне (отделения 0001 и 0010), Давташене (0054 и 0058)

В какое отделение попадёт посылка решает ВАР, это происходит вне зависимости от указанного индекса

**Comment by druidvav** [comment]
https://github.com/haywiki/haywiki.github.io/commit/11a063e022d160d07d4af164f6e728cd2ef9952d
